# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gen_logproto.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gen_logproto.proto',
  package='log_transaction_family',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12gen_logproto.proto\x12\x16log_transaction_family\"H\n\x0btransaction\x12\x15\n\rApplicationId\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0f\n\x07Message\x18\x03 \x01(\tb\x06proto3'
)




_TRANSACTION = _descriptor.Descriptor(
  name='transaction',
  full_name='log_transaction_family.transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ApplicationId', full_name='log_transaction_family.transaction.ApplicationId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='log_transaction_family.transaction.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Message', full_name='log_transaction_family.transaction.Message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

transaction = _reflection.GeneratedProtocolMessageType('transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'gen_logproto_pb2'
  # @@protoc_insertion_point(class_scope:log_transaction_family.transaction)
  })
_sym_db.RegisterMessage(transaction)


# @@protoc_insertion_point(module_scope)
