# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='application.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11\x61pplication.proto\"1\n\x0b\x61pplication\x12\x15\n\rApplicationId\x18\x01 \x01(\t\x12\x0b\n\x03Key\x18\x02 \x01(\t\"6\n\x10\x41pplicationsList\x12\"\n\x0c\x41pplications\x18\x01 \x03(\x0b\x32\x0c.applicationb\x06proto3'
)




_APPLICATION = _descriptor.Descriptor(
  name='application',
  full_name='application',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ApplicationId', full_name='application.ApplicationId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Key', full_name='application.Key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=70,
)


_APPLICATIONSLIST = _descriptor.Descriptor(
  name='ApplicationsList',
  full_name='ApplicationsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Applications', full_name='ApplicationsList.Applications', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=126,
)

_APPLICATIONSLIST.fields_by_name['Applications'].message_type = _APPLICATION
DESCRIPTOR.message_types_by_name['application'] = _APPLICATION
DESCRIPTOR.message_types_by_name['ApplicationsList'] = _APPLICATIONSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

application = _reflection.GeneratedProtocolMessageType('application', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATION,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:application)
  })
_sym_db.RegisterMessage(application)

ApplicationsList = _reflection.GeneratedProtocolMessageType('ApplicationsList', (_message.Message,), {
  'DESCRIPTOR' : _APPLICATIONSLIST,
  '__module__' : 'application_pb2'
  # @@protoc_insertion_point(class_scope:ApplicationsList)
  })
_sym_db.RegisterMessage(ApplicationsList)


# @@protoc_insertion_point(module_scope)
