# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evidence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='evidence.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65vidence.proto\"\xcd\x01\n\x08\x45vidence\x12\x18\n\x10VerifierIdentity\x18\x01 \x01(\t\x12\x16\n\x0eProverIdentity\x18\x02 \x01(\t\x12\x17\n\x0f\x41ttestationType\x18\x03 \x01(\t\x12\x19\n\x11ProverDeviceClass\x18\x04 \x01(\t\x12\x15\n\rProverVersion\x18\x05 \x01(\t\x12\x13\n\x0bMeasurement\x18\x06 \x01(\t\x12\x1c\n\x14isWarrantAttestation\x18\x07 \x01(\t\x12\x11\n\tTimestamp\x18\x08 \x01(\x05\",\n\x0c\x45videnceList\x12\x1c\n\tEvidences\x18\x01 \x03(\x0b\x32\t.Evidenceb\x06proto3')
)




_EVIDENCE = _descriptor.Descriptor(
  name='Evidence',
  full_name='Evidence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='VerifierIdentity', full_name='Evidence.VerifierIdentity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProverIdentity', full_name='Evidence.ProverIdentity', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AttestationType', full_name='Evidence.AttestationType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProverDeviceClass', full_name='Evidence.ProverDeviceClass', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ProverVersion', full_name='Evidence.ProverVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Measurement', full_name='Evidence.Measurement', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isWarrantAttestation', full_name='Evidence.isWarrantAttestation', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='Evidence.Timestamp', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=224,
)


_EVIDENCELIST = _descriptor.Descriptor(
  name='EvidenceList',
  full_name='EvidenceList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Evidences', full_name='EvidenceList.Evidences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=270,
)

_EVIDENCELIST.fields_by_name['Evidences'].message_type = _EVIDENCE
DESCRIPTOR.message_types_by_name['Evidence'] = _EVIDENCE
DESCRIPTOR.message_types_by_name['EvidenceList'] = _EVIDENCELIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Evidence = _reflection.GeneratedProtocolMessageType('Evidence', (_message.Message,), dict(
  DESCRIPTOR = _EVIDENCE,
  __module__ = 'evidence_pb2'
  # @@protoc_insertion_point(class_scope:Evidence)
  ))
_sym_db.RegisterMessage(Evidence)

EvidenceList = _reflection.GeneratedProtocolMessageType('EvidenceList', (_message.Message,), dict(
  DESCRIPTOR = _EVIDENCELIST,
  __module__ = 'evidence_pb2'
  # @@protoc_insertion_point(class_scope:EvidenceList)
  ))
_sym_db.RegisterMessage(EvidenceList)


# @@protoc_insertion_point(module_scope)
